### ISSUE TITLE
Add cloud code function to get related outcomes and reflections (for new and existing)

### ISSUE THREAD

**Issue by gjermundgaraba** [bjaanes/ExtremeResults-CloudCode#2]
Add cloud code function to get related outcomes and reflections (for new and existing).

When creating a new outcome or reflection, we need tot be able to show all related outcomes and reflections:
eg. Monday Vision:
Show Friday the last Friday Reflection (if there is any).
Perhaps show last monday vision too (if there is any)?

We need a function that returns all related outcomes and reflections for an "about-to-be-created" outcome or reflection.

Is there any magic way to use this, that doesn't require us to have type specific code? Might need changes in data model fra that.

Monday Vision:
Show Friday the last Friday Reflection (if there is any).
Perhaps show last monday vision too (if there is any)?

Daily Outcomes:
Show Monday Vision (if there is any linked up)
Perhaps show last daily outcome too (if there are any)?

Weekly Reflection:
Show Monday Vision (if there is any linked up)
Show last weeks Daily Outcomes (if there are any)?

**Comment by bjaanes** [comment]
Closed by:
https://github.com/bjaanes/ExtremeResults-CloudCode/commit/aa2e4cf4503e468671bc56810acd5175cba6ac93

**Comment by gjermundgaraba** [comment]
https://github.com/bjaanes/ExtremeResults-CloudCode/commit/aa2e4cf4503e468671bc56810acd5175cba6ac93
